menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/howiefh
  RSS: /atom.xml

widgets: 
- search
- category
- tagcloud
- calendar
- recent_posts

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-40492061-1
rss:
